//1 = safelane farm 2= can you mid 3 can you offlane 4 = jungle or farming supp 5 = supp
var heroNames = module.exports = [
    {name: "queenofpain", roles: [2, 3]},
    {name: "antimage", roles: [1]},
    {name: "kunkka", roles: [2, 3, 4]},
    {name: "lina", roles: [2, 3, 4, 5]},
    {name: "mirana", roles: [1, 2, 3, 4, 5]},
    {name: "slardar", roles: [2, 3, 4]},
    {name: "lion", roles: [4, 5]},
    {name: "phantom_assassin", roles: [1, 2]},
    {name: "tidehunter", roles: [2, 3, 4, 5]},
    {name: "witch_doctor", roles: [4, 5]},
    {name: "vengefulspirit", roles: [3, 4, 5]},
    {name: "juggernaut", roles: [1]},
    {name: "earthshaker", roles: [2, 4, 5]},
    {name: "pudge", roles: [2, 3]},
    {name: "bane", roles: [5]},
    {name: "crystal_maiden", roles: [5]},
    {name: "sven", roles: [1, 3, 4, 5]},
    {name: "skeleton_king", roles: [1, 3, 4, 5]},
    {name: "storm_spirit", roles: [1, 2]},
    {name: "sand_king", roles: [4, 5,]},
    {name: "nevermore", roles: [1, 2]},
    {name: "drow_ranger", roles: [1, 2]},
    {name: "axe", roles: [3, 4]},
    {name: "bloodseeker", roles: [2, 3, 4]},
    {name: "phantom_lancer", roles: [1]},
    {name: "razor", roles: [1, 2, 3]},
    {name: "morphling", roles: [1, 2, 3]},
    {name: "zuus", roles: [2]},
    {name: "tiny", roles: [1, 2, 3]},
    {name: "puck", roles: [2, 3]},
    {name: "windrunner", roles: [2, 3, 4]},
    {name: "lich", roles: [3, 4, 5]},
    {name: "shadow_shaman", roles: [5]},
    {name: "riki", roles: [1, 3]},
    {name: "enigma", roles: [4]},
    {name: "tinker", roles: [2]},
    {name: "sniper", roles: [1, 2]},
    {name: "necrolyte", roles: [2, 3]},
    {name: "warlock", roles: [2, 3, 4, 5]},
    {name: "beastmaster", roles: [2, 3]},
    {name: "venomancer", roles: [2, 3, 4, 5]},
    {name: "faceless_void", roles: [1, 3]},
    {name: "death_prophet", roles: [2]},
    {name: "pugna", roles: [2, 3, 4]},
    {name: "templar_assassin", roles: [2]},
    {name: "viper", roles: [2, 3]},
    {name: "luna", roles: [1, 2]},
    {name: "dragon_knight", roles: [2]},
    {name: "dazzle", roles: [5]},
    {name: "rattletrap", roles: [3, 4]},
    {name: "leshrac", roles: [2, 3, 4, 5]},
    {name: "furion", roles: [2, 3, 4]},
    {name: "life_stealer", roles: [1, 3]},
    {name: "dark_seer", roles: [3]},
    {name: "clinkz", roles: [1, 3]},
    {name: "omniknight", roles: [3, 4, 5]},
    {name: "enchantress", roles: [3, 4]},
    {name: "huskar", roles: [2, 3]},
    {name: "night_stalker", roles: [2, 3, 4]},
    {name: "broodmother", roles: [3]},
    {name: "bounty_hunter", roles: [3, 4]},
    {name: "weaver", roles: [1, 3]},
    {name: "jakiro", roles: [3, 4, 5]},
    {name: "batrider", roles: [2, 3, 4]},
    {name: "chen", roles: [4]},
    {name: "spectre", roles: [1]},
    {name: "doom_bringer", roles: [1,2, 3, 4]},
    {name: "ancient_apparition", roles: [5]},
    {name: "ursa", roles: [1, 2, 3, 4]},
    {name: "spirit_breaker", roles: [3, 4]},
    {name: "gyrocopter", roles: [1, 2, 3]},
    {name: "alchemist", roles: [1, 2, 3, 4, 5]},
    {name: "invoker", roles: [2]},
    {name: "silencer", roles: [2, 3, 4, 5]},
    {name: "obsidian_destroyer", roles: [2]},
    {name: "lycan", roles: [1, 4]},
    {name: "brewmaster", roles: [2, 3]},
    {name: "shadow_demon", roles: [5]},
    {name: "lone_druid", roles: []},
    {name: "chaos_knight", roles: [1,3]},
    {name: "treant", roles: [3, 4, 5]},
    {name: "meepo", roles: [1, 2]},
    {name: "ogre_magi", roles: [4, 5]},
    {name: "undying", roles: [3, 4]},
    {name: "rubick", roles: [4, 5]},
    {name: "disruptor", roles: [5]},
    {name: "nyx_assassin", roles: [2, 3, 4, 5]},
    {name: "naga_siren", roles: [1, 2, 3, 5]},
    {name: "keeper_of_the_light", roles: [5]},
    {name: "visage", roles: [3, 4, 5]},
    {name: "wisp", roles: [5]},
    {name: "slark", roles: [1, 2, 3]},
    {name: "medusa", roles: [1]},
    {name: "troll_warlord", roles: [1]},
    {name: "centaur", roles: [3]},
    {name: "magnataur", roles: [2, 3]},
    {name: "shredder", roles: [3]},
    {name: "bristleback", roles: [3]},
    {name: "tusk", roles: [2, 3, 4, 5]},
    {name: "skywrath_mage", roles: [2, 4, 5]},
    {name: "abaddon", roles: [3, 4, 5]},
    {name: "elder_titan", roles: [3, 4, 5]},
    {name: "legion_commander", roles: [2, 3, 4]},
    {name: "ember_spirit", roles: [1, 2]},
    {name: "earth_spirit", roles: [2, 3, 4, 5]},
    {name: "winter_wyvern", roles: [5]},
    {name: "oracle", roles: [5]},
    {name: "techies", roles: [3, 4]},
    {name: "terrorblade", roles: [1]},
    {name: "phoenix", roles: [3, 4]}
    ] 

    //attempts: 1
    //successes: 
    //207
    //various errors i have gotten
    //{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
    //{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
    //{ [Error: socket hang up] code: 'ECONNRESET' }


