//1 = safelane farm 2= can you mid 3 can you offlane 4 = jungle or farming supp 5 = supp
var heroNames = module.exports = [
    {name: "queenofpain", score: [], roles: [2, 3]},
    {name: "antimage", score: [], roles: [1]},
    {name: "kunkka", score: [], roles: [2, 3, 4]},
    {name: "lina", score: [], roles: [2, 3, 4, 5]},
    {name: "mirana", score: [], roles: [1, 2, 3, 4, 5]},
    {name: "slardar", score: [], roles: [2, 3, 4]},
    {name: "lion", score: [], roles: [4, 5]},
    {name: "phantom_assassin", score: [], roles: [1, 2]},
    {name: "tidehunter", score: [], roles: [2, 3, 4, 5]},
    {name: "witch_doctor", score: [], roles: [4, 5]},
    {name: "vengefulspirit", score: [], roles: [3, 4, 5]},
    {name: "juggernaut", score: [], roles: [1]},
    {name: "earthshaker", score: [], roles: [2, 4, 5]},
    {name: "pudge", score: [], roles: [2, 3]},
    {name: "bane", score: [], roles: [5]},
    {name: "crystal_maiden", score: [], roles: [5]},
    {name: "sven", score: [], roles: [1, 3, 4, 5]},
    {name: "skeleton_king", score: [], roles: [1, 3, 4, 5]},
    {name: "storm_spirit", score: [], roles: [1, 2]},
    {name: "sand_king", score: [], roles: [4, 5,]},
    {name: "nevermore", score: [], roles: [1, 2]},
    {name: "drow_ranger", score: [], roles: [1, 2]},
    {name: "axe", score: [], roles: [3, 4]},
    {name: "bloodseeker", score: [], roles: [2, 3, 4]},
    {name: "phantom_lancer", score: [], roles: [1]},
    {name: "razor", score: [], roles: [1, 2, 3]},
    {name: "morphling", score: [], roles: [1, 2, 3]},
    {name: "zuus", score: [], roles: [2]},
    {name: "tiny", score: [], roles: [1, 2, 3]},
    {name: "puck", score: [], roles: [2, 3]},
    {name: "windrunner", score: [], roles: [2, 3, 4]},
    {name: "lich", score: [], roles: [3, 4, 5]},
    {name: "shadow_shaman", score: [], roles: [5]},
    {name: "riki", score: [], roles: [1, 3]},
    {name: "enigma", score: [], roles: [4]},
    {name: "tinker", score: [], roles: [2]},
    {name: "sniper", score: [], roles: [1, 2]},
    {name: "necrolyte", score: [], roles: [2, 3]},
    {name: "warlock", score: [], roles: [2, 3, 4, 5]},
    {name: "beastmaster", score: [], roles: [2, 3]},
    {name: "venomancer", score: [], roles: [2, 3, 4, 5]},
    {name: "faceless_void", score: [], roles: [1, 3]},
    {name: "death_prophet", score: [], roles: [2]},
    {name: "pugna", score: [], roles: [2, 3, 4]},
    {name: "templar_assassin", score: [], roles: [2]},
    {name: "viper", score: [], roles: [2, 3]},
    {name: "luna", score: [], roles: [1, 2]},
    {name: "dragon_knight", score: [], roles: [2]},
    {name: "dazzle", score: [], roles: [5]},
    {name: "rattletrap", score: [], roles: [3, 4]},
    {name: "leshrac", score: [], roles: [2, 3, 4, 5]},
    {name: "furion", score: [], roles: [2, 3, 4]},
    {name: "life_stealer", score: [], roles: [1, 3]},
    {name: "dark_seer", score: [], roles: [3]},
    {name: "clinkz", score: [], roles: [1, 3]},
    {name: "omniknight", score: [], roles: [3, 4, 5]},
    {name: "enchantress", score: [], roles: [3, 4]},
    {name: "huskar", score: [], roles: [2, 3]},
    {name: "night_stalker", score: [], roles: [2, 3, 4]},
    {name: "broodmother", score: [], roles: [3]},
    {name: "bounty_hunter", score: [], roles: [3, 4]},
    {name: "weaver", score: [], roles: [1, 3]},
    {name: "jakiro", score: [], roles: [3, 4, 5]},
    {name: "batrider", score: [], roles: [2, 3, 4]},
    {name: "chen", score: [], roles: [4]},
    {name: "spectre", score: [], roles: [1]},
    {name: "doom_bringer", score: [], roles: [1,2, 3, 4]},
    {name: "ancient_apparition", score: [], roles: [5]},
    {name: "ursa", score: [], roles: [1, 2, 3, 4]},
    {name: "spirit_breaker", score: [], roles: [3, 4]},
    {name: "gyrocopter", score: [], roles: [1, 2, 3]},
    {name: "alchemist", score: [], roles: [1, 2, 3, 4, 5]},
    {name: "invoker", score: [], roles: [2]},
    {name: "silencer", score: [], roles: [2, 3, 4, 5]},
    {name: "obsidian_destroyer", score: [], roles: [2]},
    {name: "lycan", score: [], roles: [1, 4]},
    {name: "brewmaster", score: [], roles: [2, 3]},
    {name: "shadow_demon", score: [], roles: [5]},
    {name: "lone_druid", score: [], roles: []},
    {name: "chaos_knight", score: [], roles: [1,3]},
    {name: "treant", score: [], roles: [3, 4, 5]},
    {name: "meepo", score: [], roles: [1, 2]},
    {name: "ogre_magi", score: [], roles: [4, 5]},
    {name: "undying", score: [], roles: [3, 4]},
    {name: "rubick", score: [], roles: [4, 5]},
    {name: "disruptor", score: [], roles: [5]},
    {name: "nyx_assassin", score: [], roles: [2, 3, 4, 5]},
    {name: "naga_siren", score: [], roles: [1, 2, 3, 5]},
    {name: "keeper_of_the_light", score: [], roles: [5]},
    {name: "visage", score: [], roles: [3, 4, 5]},
    {name: "wisp", score: [], roles: [5]},
    {name: "slark", score: [], roles: [1, 2, 3]},
    {name: "medusa", score: [], roles: [1]},
    {name: "troll_warlord", score: [], roles: [1]},
    {name: "centaur", score: [], roles: [3]},
    {name: "magnataur", score: [], roles: [2, 3]},
    {name: "shredder", score: [], roles: [3]},
    {name: "bristleback", score: [], roles: [3]},
    {name: "tusk", score: [], roles: [2, 3, 4, 5]},
    {name: "skywrath_mage", score: [], roles: [2, 4, 5]},
    {name: "abaddon", score: [], roles: [3, 4, 5]},
    {name: "elder_titan", score: [], roles: [3, 4, 5]},
    {name: "legion_commander", score: [], roles: [2, 3, 4]},
    {name: "ember_spirit", score: [], roles: [1, 2]},
    {name: "earth_spirit", score: [], roles: [2, 3, 4, 5]},
    {name: "winter_wyvern", score: [], roles: [5]},
    {name: "oracle", score: [], roles: [5]},
    {name: "techies", score: [], roles: [3, 4]},
    {name: "terrorblade", score: [], roles: [1]},
    {name: "phoenix", score: [], roles: [3, 4]}
    ] 

    //attempts: 1
    //successes: 
    //207
    //various errors i have gotten
    //{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
    //{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
    //{ [Error: socket hang up] code: 'ECONNRESET' }


